name: Build and publish daily Docker images

on:
  schedule:
  - cron: "0 4 * * *" # Run every day at 4am UTC

permissions:
  packages: write

jobs:
  imagepublisher:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get current date for image tag
      run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ env.DATE }}
